# -*- coding: utf-8 -*-
"""Q2_Way Too Long Words.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C_O015dfyVs1zLoV7DfKYQvupsuEH-Oi
"""

no_of_words = int(input())

for _ in range(no_of_words):
    word = input().strip()
    if len(word) > 10:
        print(f"{word[0]}{len(word) - 2}{word[-1]}")
    else:
        print(word)