# -*- coding: utf-8 -*-
"""Q1_Watermelon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C_O015dfyVs1zLoV7DfKYQvupsuEH-Oi
"""

weight = int(input())

if weight % 2 == 0 and weight > 2:
    print("YES")
else:
    print("NO")